version: "3.8"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8585:8585"

volumes:
  data:

