package main

import (
	"github.com/angrynerds-pl/kpz-contactless-restaurant-backend/api/db"
	"github.com/angrynerds-pl/kpz-contactless-restaurant-backend/api/handler"
	"github.com/angrynerds-pl/kpz-contactless-restaurant-backend/api/router"
	"github.com/angrynerds-pl/kpz-contactless-restaurant-backend/api/store"
	"log"

	_ "github.com/angrynerds-pl/kpz-contactless-restaurant-backend/docs" // docs is generated by Swag CLI, you have to import it
	echoSwagger "github.com/swaggo/echo-swagger"                         // echo-swagger middleware
)

// @title Restaurant backend API server
// @version 0.1.0
// @description This is a Restaurant backend RESTful API documentation.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8585
// @BasePath /v1
// @query.collection.format multi

// @securityDefinitions.basic BasicAuth

// @x-extension-openapi {"example": "value on a json format"}
func main() {

	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/v1")

	d, err := db.New()
	if err != nil {
		log.Fatalf("could not connect to db: %v", err)
	}

	err = db.AutoMigrate(d)
	if err != nil {
		log.Fatalf("Could not automigrate db. Err = %v", err)

	}

	us := store.NewUserStore(d)
	rs := store.NewRestaurantStore(d)
	h := handler.NewHandler(us, rs)
	h.Register(v1)
	r.Logger.Fatal(r.Start(":8585"))
}
